### ISSUE TITLE
Adding custom algo

### ISSUE THREAD

**Issue by coolindark** [zone117x/node-multi-hashing#43]
Hello. It try to add skunkhash but it returns with the error below. What am i missing? edited all js & cc...

/home/coolindark/unomp/node_modules/merged-pooler/lib/algoProperties.js:248
                return multiHashing.skunkhash.apply(this, arguments);
                                              ^
TypeError: Cannot call method 'apply' of undefined
    at /home/coolindark/unomp/node_modules/merged-pooler/lib/algoProperties.js:248:47
    at JobManager.processShare (/home/coolindark/unomp/node_modules/merged-pooler/lib/jobManager.js:263:26)
    at null.<anonymous> (/home/coolindark/unomp/node_modules/merged-pooler/lib/pool.js:623:46)
    at EventEmitter.emit (events.js:117:20)
    at handleSubmit (/home/coolindark/unomp/node_modules/merged-pooler/lib/stratum.js:175:15)
    at handleMessage (/home/coolindark/unomp/node_modules/merged-pooler/lib/stratum.js:88:17)
    at /home/coolindark/unomp/node_modules/merged-pooler/lib/stratum.js:248:25
    at Array.forEach (native)
    at Socket.<anonymous> (/home/coolindark/unomp/node_modules/merged-pooler/lib/stratum.js:234:26)

Thank you!

**Comment by krisklosterman** [comment]
please keep in mind your installed node version and the required node version of this fork (0.10.x).

I don't think thats your issue, from the error its stating that multiHashing.skunkhash is undefined.
