### ISSUE TITLE
Failed at the multi-hashing@0.0.9 install script.

### ISSUE THREAD

**Issue by cryptomaxsun** [zone117x/node-multi-hashing#54]
npm install multi-hashing

                                  ^
```
/root/.node-gyp/9.10.1/include/node/v8.h:5525:34: note:   no known conversion for argumen
multihashing.target.mk:143: recipe for target 'Release/obj.target/multihashing/multihashi
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 3.13.0-109-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/npm:-lifecycle/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/max/pool/node_modules/multi-hashing
gyp ERR! node -v v9.10.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! multi-hashing@0.0.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the multi-hashing@0.0.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```
Ubuntu 16.04
node -v
v9.10.1

nodejs -v
v4.2.6

npm -v
5.8.0

nvm ls
    v0.10.25
    v0.10.48
->    system
default -> 0.10.48 (-> v0.10.48)

how fix?

**Comment by fmarines** [comment]
I have the same error, any way to fix this? npm latest version is 0.0.4 where is the 0.0.9

**Comment by monam7** [comment]
You got any solution? Got the same problem..
